### PR TITLE
feat(localization): update pseudo translation

### PR DESCRIPTION
**Pull request by jona7150**
Updated translation using Jenkins. Please review and merge @mstefarov @dotMorten 

 CC: @michi6571 @masa6674

### CODE REVIEW

**Review by dotMorten — APPROVED** [review]
Looks good. We cannot merge pseudo translations though.

**Comment by jona7150** [comment]
Added another commit for translation updates: be62bd2

**Review by mstefarov — COMMENTED** [review]
Spot-checking the languages that I understand, I see that "PopupViewerViewHyperlinkText" has been mistranslated in a couple of them.  The word "View" is meant to be an imperative verb, describing an action that will happen when a button is clicked.  German translation gets it right with "Anzeigen" but others are wrong:

- Russian file has "Вид" (a view of something) instead of the conventional "Открыть" (open this) or "Просмотреть" (view this).
- Ukrainian has "Огляд" (an overview) instead of the expected "Відкрити" (open this) or "Переглянути" (view this).
- Japanese just has "ビュー" ("byoo"), a transliteration of "view", instead of a real translation like "開く" (open this) or "閲覧" (browse this).

Is this one of those cases where people doing the translation did not have the English `<comment>` available to reference?

**Comment by michi6571** [comment]
@mstefarov Thank you for your concerns: thttps://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/pull/608#pullrequestreview-2344947011
We will ask our LSP (translators) and SME (distributors) to review if the current translations need to be updated.  

@dotMorten. Please let us know if we still have time to update the translations for this release.   

 cc @masa6674

**Comment by dotMorten** [comment]
@michi6571 we still got a month or so to address this.

**Comment by michi6571** [comment]
Thank you, @dotMorten.  We will let you know if the current translations need to be updated, and we need to add another commit. 

cc @mstefarov @masa6674

**Comment by michi6571** [comment]
@dotMorten @mstefarov Several translators and distributors have reviewed and updated the translations.  We have run another Generate build and added a new commit: 
https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/pull/608/commits/eaa5e9c60caf750e0ecb66003ef3ab62a6368bd5

cc @masa6674

**Pull request merged**
